### ISSUE TITLE
Something wrong with data formatter?

### ISSUE THREAD

**Issue by TasmaniaKrama** [ClimbsRocks/machineJS#153]
So I am quite a noob in this machine learning but I really tried hard and followed exactly on how to install machineJS also it took me a while to format the data but I formatted the data as it was requested in the https://github.com/ClimbsRocks/data-formatter 
If needed I could upload the data I formatted but I seriously have no idea what I am doing wrong here.

C:\Users\Filip\machineJS>node machineJS.js final.csv --predict test123.csv
thanks for inviting us along on your machine learning journey!

heard an error!
{ [Error: AttributeError: 'module' object has no attribute 'MaxAbsScaler']
  traceback: 'Traceback (most recent call last):\r\n  File "C:\\Users\\Filip\\ma
chineJS\\node_modules\\data-formatter\\mainPythonProcess.py", line 27, in <modul
e>\r\n    from helperFunctions import minMax\r\n  File "C:\\Users\\Filip\\machin
eJS\\node_modules\\data-formatter\\helperFunctions\\minMax.py", line 8, in <modu
le>\r\n    max_abs_scaler = preprocessing.MaxAbsScaler()\r\nAttributeError: \'mo
dule\' object has no attribute \'MaxAbsScaler\'\r\n',
  executable: 'python',
  options: null,
  script: 'C:\\Users\\Filip\\machineJS\\node_modules\\data-formatter\\mainPython
Process.py',
  args: [ '{"trainingData":"final.csv","testingData":"test123.csv","trainingPret
tyName":"final","testingPrettyName":"test123","joinFileName":"","on":false,"allF
eatureCombinations":false,"keepAllFeatures":false,"outputFolder":"C:\\\\Users\\\
\Filip\\\\machineJS\\\\pySetup\\\\data-formatterResults","test":false,"verbose":
1,"join":false}' ],
  exitCode: 1 }
Here are the fileNames from data-formatter. If you want to skip the data-formatt
er part next time you want to play with this dataset, copy and paste this object
 into machineJS/pySetup/testingFileNames.js, following the instructions included
 in that file.
{}
{ [Error: KeyError: 'X_train']
  traceback: 'Traceback (most recent call last):\r\n  File "C:\\Users\\Filip\\ma
chineJS\\pySetup\\splitDatasets.py", line 17, in <module>\r\n    XFileName = fil
eNames[\'X_train\']\r\nKeyError: \'X_train\'\r\n',
  executable: 'python',
  options: null,
  script: 'C:\\Users\\Filip\\machineJS\\pySetup\\splitDatasets.py',
  args:
   [ 'C:\\Users\\Filip\\machineJS\\ignoreMe.csv',
     '{"_":["C:\\\\Users\\\\Filip\\\\machineJS\\\\machineJS.js","final.csv"],"pr
edict":"test123.csv","dev":false,"computerTotalCPUs":4,"machineJSLocation":"C:\\
\\Users\\\\Filip\\\\machineJS","dataFile":"final.csv","dataFileName":"final.csv"
,"dataFilePretty":"final","binaryOutput":false,"outputFileName":"final","join":"
","on":"","allFeatureCombinations":"","keepAllFeatures":"","dfOutputFolder":"C:\
\\\Users\\\\Filip\\\\machineJS\\\\pySetup\\\\data-formatterResults","matrixOutpu
t":"","testFileName":"test123.csv","testFilePretty":"test123","testOutputFileNam
e":"test123","searchPercent":0.3,"validationPercent":0.3,"numRounds":10,"numIter
ationsPerRound":10,"predictionsFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\pre
dictions\\\\test123","validationFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\pr
edictions\\\\test123\\\\validation","bestClassifiersFolder":"C:\\\\Users\\\\Fili
p\\\\machineJS\\\\pySetup\\\\bestClassifiers\\\\final","ensemblerOutputFolder":"
C:\\\\Users\\\\Filip\\\\machineJS","validationRound":false,"ensemblerArgs":{"inp
utFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\predictions\\\\test123","outputF
older":"C:\\\\Users\\\\Filip\\\\machineJS","validationFolder":"C:\\\\Users\\\\Fi
lip\\\\machineJS\\\\predictions\\\\test123\\\\validation","fileNameIdentifier":"
final","validationRound":true},"numCPUs":3,"longTrainThreshold":0.97,"continueTo
TrainThreshold":0.97,"alreadyFormatted":false}',
     '{}' ],
  exitCode: 1 }
{ [Error: ImportError: No module named joblib]
  traceback: 'Traceback (most recent call last):\r\n  File "C:\\Users\\Filip\\ma
chineJS\\pySetup\\training.py", line 6, in <module>\r\n    import joblib\r\nImpo
rtError: No module named joblib\r\n',
  executable: 'python',
  options: null,
  script: 'C:\\Users\\Filip\\machineJS\\pySetup\\training.py',
  args:
   [ 'C:\\Users\\Filip\\machineJS\\final.csv',
     '{"_":["C:\\\\Users\\\\Filip\\\\machineJS\\\\machineJS.js","final.csv"],"pr
edict":"test123.csv","dev":false,"computerTotalCPUs":4,"machineJSLocation":"C:\\
\\Users\\\\Filip\\\\machineJS","dataFile":"final.csv","dataFileName":"final.csv"
,"dataFilePretty":"final","binaryOutput":false,"outputFileName":"final","join":"
","on":"","allFeatureCombinations":"","keepAllFeatures":"","dfOutputFolder":"C:\
\\\Users\\\\Filip\\\\machineJS\\\\pySetup\\\\data-formatterResults","matrixOutpu
t":"","testFileName":"test123.csv","testFilePretty":"test123","testOutputFileNam
e":"test123","searchPercent":0.3,"validationPercent":0.3,"numRounds":10,"numIter
ationsPerRound":10,"predictionsFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\pre
dictions\\\\test123","validationFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\pr
edictions\\\\test123\\\\validation","bestClassifiersFolder":"C:\\\\Users\\\\Fili
p\\\\machineJS\\\\pySetup\\\\bestClassifiers\\\\final","ensemblerOutputFolder":"
C:\\\\Users\\\\Filip\\\\machineJS","validationRound":false,"ensemblerArgs":{"inp
utFolder":"C:\\\\Users\\\\Filip\\\\machineJS\\\\predictions\\\\test123","outputF
older":"C:\\\\Users\\\\Filip\\\\machineJS","validationFolder":"C:\\\\Users\\\\Fi
lip\\\\machineJS\\\\predictions\\\\test123\\\\validation","fileNameIdentifier":"
final","validationRound":true},"numCPUs":3,"longTrainThreshold":0.97,"continueTo
TrainThreshold":0.97,"alreadyFormatted":false}',
     '{}',
     'clRfGini',
     undefined,
     0 ],
  exitCode: 1 }
kicking off the process of making predictions on the predicting data set for: cl
RfGini
we heard an unexpected shutdown event that is causing everything to close
C:\Users\Filip\machineJS\shutDown.js:19
      throw error;
      ^

TypeError: Cannot read property 'longTrainScore' of undefined
    at startPredictionsScript (C:\Users\Filip\machineJS\pySetup\utils.js:129:58)

    at Object.module.exports.makePredictions (C:\Users\Filip\machineJS\pySetup\u
tils.js:144:5)
    at Object.module.exports.makePredictions (C:\Users\Filip\machineJS\pySetup\c
ontrollerPython.js:142:11)
    at C:\Users\Filip\machineJS\pySetup\controllerPython.js:32:24
    at emitFinishedTrainingCallback (C:\Users\Filip\machineJS\pySetup\utils.js:8
7:7)
    at C:\Users\Filip\machineJS\pySetup\utilsPyShell.js:60:7
    at null._endCallback (C:\Users\Filip\machineJS\node_modules\python-shell\ind
ex.js:148:25)
    at ChildProcess.<anonymous> (C:\Users\Filip\machineJS\node_modules\python-sh
ell\index.js:99:35)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)

C:\Users\Filip\machineJS>

**Comment by ClimbsRocks** [comment]
I'll respond better later when I'm at a computer, but it looks like Sci kit
learn is not recognized on your computer.

**Comment by TasmaniaKrama** [comment]
That is really strange, I installed python x,y and then installed scikit and actually did some tutorials and used the data (8x8 images for numbers) to train and it was all fine.

**Comment by ClimbsRocks** [comment]
Hi @TasmaniaKrama! 

Thanks for using the library, and giving feedback. 

The initial error you're getting (before it cascades through many other part of the project) is: 

"{ [Error: AttributeError: 'module' object has no attribute 'MaxAbsScaler']"

MaxAbsScaler is a bit of functionality we import from scikit-learn, and for some reason it's not being found on your system. It was recently introduced in v0.17, so my current guess is that you have an older (working) version of scikit-learn installed on your machine that the script is trying to pull from. It's entirely possible you might have two versions of scikit-learn installed if they were installed in different ways, or with two different user credentials (I've seen this pop up with sudo, anaconda, and people who just have multiple accounts on the same machine). 

I'd recommend uninstalling scikit-learn using whatever methods you did to install it, and then reinstalling it fresh from GitHub. You can use the instructions in installPythonDependencies.sh if you'd like for installing from GitHub, but it's probably best to just do it from the command line, since the shell script I provided might be installing as a different user. 

Let me know how it goes!
preston

**Comment by TasmaniaKrama** [comment]
C:\Users\Filip>git clone https://github.com/ClimbsRocks/machineJS.git
Cloning into 'machineJS'...
remote: Counting objects: 2565, done.
rRemote: Total 2565 (delta 0), reused 0 (delta 0), pack-reused 2565eceiving obje
Receiving objects: 100% (2565/2565), 459.58 KiB | 269.00 KiB/s, done.

Resolving deltas: 100% (1820/1820), done.
Checking connectivity... done.

C:\Users\Filip>cd machineJS

C:\Users\Filip\machineJS>npm install
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
babyparse@0.4.3 node_modules\babyparse

python-shell@0.2.0 node_modules\python-shell

minimist@1.2.0 node_modules\minimist

data-formatter@1.6.2 node_modules\data-formatter

mkdirp@0.5.1 node_modules\mkdirp
└── minimist@0.0.8

chai@3.5.0 node_modules\chai
├── type-detect@1.0.0
├── assertion-error@1.0.1
└── deep-eql@0.1.3 (type-detect@0.1.1)

longjohn@0.2.11 node_modules\longjohn
└── source-map-support@0.3.2 (source-map@0.1.32)

csv@0.4.6 node_modules\csv
├── csv-generate@0.0.6
├── stream-transform@0.1.1
├── csv-stringify@0.0.8
└── csv-parse@1.0.2

rimraf@2.5.2 node_modules\rimraf
└── glob@7.0.0 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0
.4, minimatch@3.0.0)

data-for-tests@0.0.3 node_modules\data-for-tests

mocha@2.4.5 node_modules\mocha
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── diff@1.4.0
├── growl@1.8.1
├── supports-color@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

fast-csv@0.6.0 node_modules\fast-csv
├── is-extended@0.0.10
├── object-extended@0.0.7 (array-extended@0.0.11)
├── string-extended@0.0.8 (date-extended@0.0.6, array-extended@0.0.11)
└── extended@0.0.6 (extender@0.0.10)

ensembler@0.9.1 node_modules\ensembler
├── byline@4.2.1
├── machinejs@0.9.4
├── fs-extra@0.26.5 (path-is-absolute@1.0.0, jsonfile@2.2.3, klaw@1.1.3, gracefu
l-fs@4.1.3)
└── mathjs@2.7.0 (tiny-emitter@1.0.2, fraction.js@3.2.5, decimal.js@4.0.4, typed
-function@0.10.3)

C:\Users\Filip\machineJS>installPythonDependencies.sh

C:\Users\Filip\machineJS>



So this was during the installing (Iremoved everything both python x,y and machineJS)

However now once I run it I still get an error but at least it is shorter and different (so it's a plus :D )



Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Filip>cd machineJS

C:\Users\Filip\machineJS>node machineJS.js e0.csv --predict e1.csv
thanks for inviting us along on your machine learning journey!

we heard an unexpected shutdown event that is causing everything to close
C:\Users\Filip\machineJS\shutDown.js:19
      throw error;
      ^

Error: spawn python ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)



Do you happen to  have some example of train data and test data? Perhaps I am stupid (probably) and I  am labeling it incorrectly. (the ID, Output Regression, Continuous etc.) I am doing the editing in excel and saving it as csv.

Thanks for your time :)

**Comment by ClimbsRocks** [comment]
Hi @TasmaniaKrama,

It looks like there's probably still an issue with the install somewhere. 

I haven't had a chance to test this on a Windows computer, so I'm glad to have a collaborator in this! It seems that it might be having trouble finding Python to launch a child process. 

Try some of the suggestions in this issue thread: 
https://github.com/nodejs/node-gyp/issues/277

**Comment by ClimbsRocks** [comment]
Hi @TasmaniaKrama,

Let me know how this is going, and if I can help troubleshoot with you in any way!

**Comment by TasmaniaKrama** [comment]
Hey, I was away for some time but here is what happened.

I decided to use VB and install linux on it however when I did setup everything there was still trouble when trying to use pip to install certain modules.
I think there was problems with xgboost, and pip version or something. I might reinstall the linux later and try again. The problem is that all these thing require some previous installations and since I am new to all of this it's hard for me to know what exactly I should be installing and in what order.

**Comment by ClimbsRocks** [comment]
@TasmaniaKrama yeah, i was afraid we'd run into that. 

i just updated the install sequence, so that it more heavily leverages python's popular package manager pip. hopefully that should make the install easier. if you're up for trying it again (on a linux box- i just found some new issues that'll prevent it from running on a windows machine still), i'd love to hear any issues you run into!

if you do try it again, start with a fresh install following the directions in the README. 

Thanks for responding! the feedback is really helpful to make this easier for everyone (which is the whole point of this project).

**Comment by TasmaniaKrama** [comment]
I am a total noob for linux so I have almost zero knowledge of it.

Installing mint now, and as I recall I had to install the git thing and then use git clone command + npm thing had to be installed.. Anyways, I will try now step by step with your directions and if it won't work then might I ask which linux distro you are using?

**Comment by ClimbsRocks** [comment]
interesting. thanks for following up! 

1. my linux distro- i'm just on a mac :)
2. up until the xgboost error, did those packages install properly after spitting out those warnings?
3. it's odd, because i don't specify any version of xgboost, so i'm not sure why it's choking on that. try running `pip install xgboost 0.4a30` to see if it installs alright when we manually specify a version. 

worst case scenario, we can just comment out xgboost. if everything else is running, try just going to pySetup/classifierList.js and commenting out XGBoost wherever you see it (and adjusting the commas in the surrounding lines if necessary). we'll probably have to comment it out in one or two other places as well (like pySetup/makeClassifiers.py), but they should throw some pretty obvious errors and be easy to find.

**Comment by TasmaniaKrama** [comment]
Running the 0.4a30 xgboost yields the same error.

And about the previous packages, not really sure how to answer that one. It seems like they didn't since a lot of errors were thrown.
